name: Build with Emscripten and CMake

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        # Make sure to set a version number!
        version: 1.38.40
        # This is the name of the cache folder.
        # The cache folder will be placed in the build directory,
        #  so make sure it doesn't conflict with anything!
        actions-cache-folder: 'emsdk-cache'
    
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
    
    - name: Verify em++
      run: |
        em++ --version

    - name: Verify CMake
      run: |
        cmake --version

    - name: Build project with CMake and Emscripten
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
