name: Build with Emscripten and CMake

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Emscripten
      run: |
        sudo apt-get update
        sudo apt-get install -y emscripten
    
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
    
    - name: Verify em++
      run: |
        em++ --version

    - name: Verify CMake
      run: |
        cmake --version

    - name: Build project with CMake and Emscripten
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
